### ISSUE TITLE
Idea for related plugin - local folder

### ISSUE THREAD

**Issue by javiavid** [alangrainger/obsidian-google-photos#19]
I think your plugin is a great idea, but many people who use obsidian use it for privacy.
Would it be possible to create something similar but for local folders?

Perhaps the date could be read directly from the file name to make it easier.

**Comment by alangrainger** [comment]
Yes that's completely possible, and I encourage you to have a go creating it. Feel free to fork my repo and use any of the code in it. (And in case you're going to say "But I'm not a developer" ... neither was I until I started working on my first personal project just like this.)

It's out of scope for this plugin, as I wrote this because I do specifically want to interact with Google Photos.
