### ISSUE TITLE
Create a command to integrate with Banners Plugin.

### ISSUE THREAD

**Issue by DryIce1** [alangrainger/obsidian-google-photos#4]
Hi Alan,

Could I ask you to create a new command that works seamlessly with the banners plugin?

Specifically, the command should 
1. retrieve the `https://lh3.googleusercontent.com/` photo link
2. append the link to a YAML key `banner: `, and 
3. paste all of that on line 2 of the current markdown file (ie within the YAML). 

example: 
```
banner: "https://lh3.googleusercontent.com/i8lgK4OHdBc9EJWgJCddnnRealy10N-3MJmW3Xfb6UYsyZrf-K6UbZ7OY2mIpAknOEbNHxZrN3CUKaj37meuJIF2fCitA7QN0YRND0dcBLOEX1VebXOQTejVS4cq3tkgPDcVTzTcjbM=w1500-h750-no"
```

But can I also congratulate you on producing a very slick, frictionless and useable plugin that integrates really well already with a ubiquitous product, google photos. Fantastic, and well done!

**Comment by alangrainger** [comment]
Please correct me if I'm wrong, but the link you've quoted above is from a publicly shared Google Photos image, not one you've added from your own photos using my plugin.

The URLs that can be generated through the Photos API are only temporarily available. That's why I download the thumbnail locally instead of offering the option to embed a remote version. Those links expire after a fairly short period of time.

You can contrast that with the method I use in my previous Templater script, which generates thumbnails which are available indefinitely, and could absolutely be used for your YAML creation.

You can find that script here, and modify it to suit:

https://file.obsidianshare.com/82b354952349d6c6f07f693d53c57771.html
