### ISSUE TITLE
Feature request: Photo Slideshow for a given album

### ISSUE THREAD

**Issue by scottTomaszewski** [alangrainger/obsidian-google-photos#47]
I have a use case where I want to have a google photos slideshow for a Google Photos Album, similar to a digital photo frame.

Basic setting would be the album selection and duration to show each photo.

Thanks!

**Comment by alangrainger** [comment]
Hi @scottTomaszewski that's a great suggestion.

I don't plan to add this any time soon, but please can you create a Feature Request suggestion here so that others can vote it up and potentially someone else might be interested in coding it up and submitting a pull request:

https://github.com/alangrainger/obsidian-google-photos/discussions/categories/vote-for-upcoming-features
