### ISSUE TITLE
Suggestion: Embed remote images instead of downloading a local thumbnail

### ISSUE THREAD

**Issue by khanhtoan529** [alangrainger/obsidian-google-photos#6]
It would be great if image could be embedded by using an image link. Some people (including me) don't want to add more images to the attachments folder if it is not neccessary.

Another way I think is to upload thumbnails to the image hosting service (https://github.com/gavvvr/obsidian-imgur-plugin). What do you think?

**Comment by khanhtoan529** [comment]
Ah, I get the reason why you have to download local thumbnails at #4. But I think uploading thumbnails to the image hosting service will help a lot.

**Comment by alangrainger** [comment]
Adding the entire Imgur integration into this repo would definitely be out of scope and add a bunch of bloat. However it might be a very simple solution to have an option for the Google Photos plugin to paste the image data rather than saving a file - and then the existing Imgur plugin might automatically pick that up.

Do you want to clone the repo and try adding that? If it works, make a pull request and I'll add that in 👍

**Comment by khanhtoan529** [comment]
I will wait here because I'm not a developer 😅 I hope someone will find this useful and do some work on it.

**Comment by alangrainger** [comment]
Don't let that stop you - I learned Javascript for a personal project and before that I had never done any development. And I took a Typescript course on Udemy to learn how to make plugins for Obsidian, since I'd never used Typescript before :)
